
-- Use Case 1 view
WITH PORTFOLIOS AS (
  SELECT *
  FROM DL_ESG_DEV.CUSTOMER.PORTFOLIO
  WHERE P_ID IN (SELECT PORTFOLIO_ID
  FROM DL_ESG_DEV.CUSTOMER.CUSTOMER
  WHERE C_ID IN (SELECT CUS.C_ID 
  FROM DL_ESG_DEV.ESG_CONFIGURATION.USER_TABLE CUS 
  WHERE CUS.USERNAME in ('nauman')))
)
SELECT DISTINCT PORTFOLIOS.TICKER, ASS."Name", ASS.LATEST_PRICE, ASS.ENVIRONMENTAL, SOCIAL, GOVERNANCE, MONTH_1, MONTH_2, MONTH_3, MONTH_4, MONTH_5, MONTH_6
FROM PORTFOLIOS
LEFT JOIN DM_ESG_DEV.ESG_MODELS.AVG_STOCK_SCORE ASS
    ON ASS.TICKER = PORTFOLIOS.TICKER
WHERE ASS."Name" IS NOT NULL;

-- KPI Development (Refer to box for business logic)
-- KPI: 19, 20, 21, 22
SELECT AVG(tse."esg_e"), AVG(tse."esg_s"), AVG(tse."esg_g"), AVG(tse."esg")
FROM DL_ESG_DEV.CUSTOMER.PORTFOLIO p
LEFT JOIN DL_ESG_DEV.ESG.TRIAL_SCO_ESG_262 tse
    ON p.TICKER = tse."ticker";
   
   
-- KPI: 27, 28, 29, 30 ()
SELECT tse."industry", AVG(tse."esg_e"), AVG(tse."esg_s"), AVG(tse."esg_g"), AVG(tse."esg")
FROM DL_ESG_DEV.ESG.TRIAL_SCO_ESG_262 tse
GROUP BY tse."industry";


-- KPI: 23, 24, 25, 36 (top 25 percent quartile)
WITH AGG_PORT AS (   
SELECT P_ID, 
        AVG(tse."esg") as esg, 
        AVG(tse."esg_e") as esg_e, 
        AVG(tse."esg_s") as esg_s, 
        AVG(tse."esg_g") as esg_g
FROM DL_ESG_DEV.CUSTOMER.PORTFOLIO p
LEFT JOIN DL_ESG_DEV.ESG.TRIAL_SCO_ESG_262 tse
    ON p.TICKER = tse."ticker"
GROUP BY P_ID
), QUARTILES_ESG AS (    
SELECT
        AGG_PORT.*,
		NTILE(4) OVER (ORDER BY ESG DESC) AS q_esg,
        NTILE(4) OVER (ORDER BY ESG_E DESC) AS q_esg_e,
        NTILE(4) OVER (ORDER BY ESG_S DESC) AS q_esg_s,
        NTILE(4) OVER (ORDER BY ESG_G DESC) AS q_esg_g
	FROM
		AGG_PORT
)
SELECT AVG(CASE WHEN Q_ESG = 1 THEN ESG END) as AVG_ESG,
  AVG(CASE WHEN Q_ESG_E = 1 THEN ESG_E END) as AVG_ESG_E,
  AVG(CASE WHEN Q_ESG_S = 1 THEN ESG_S END) as AVG_ESG_S,
  AVG(CASE WHEN Q_ESG_G = 1 THEN ESG_G END) as AVG_ESG_G
FROM QUARTILES_ESG
;
